<?php

    // https://github.com/TYPO3-Documentation/t3docs-codesnippets
    // ddev exec vendor/bin/typo3  restructured_api_tools:php_domain public/fileadmin/TYPO3CMS-Reference-CoreApi/Documentation/

return [
    [
        'action' => 'createPhpClassDocsAll',
        'namespace' => 'TYPO3\CMS\Adminpanel',
        'mode' => HaydenPierce\ClassFinder\ClassFinder::RECURSIVE_MODE,
        'pathMode' => T3docs\RestructuredApiTools\Util\CodeSnippetCreator::RECURSIVE_PATH,
        'gitHubLink' => 'https://github.com/TYPO3/typo3/blob/main/typo3/sysext/adminpanel/Classes/',
        'mainNamespace' => 'TYPO3\\CMS\\Adminpanel\\',
        'overwriteRst' => true,
        'overwriteIndex' => true,
        'path' => 'Api/Adminpanel/',
    ],
    [
        'action' => 'createPhpClassDocsAll',
        'namespace' => 'TYPO3\CMS\Backend',
        'mode' => HaydenPierce\ClassFinder\ClassFinder::RECURSIVE_MODE,
        'pathMode' => T3docs\RestructuredApiTools\Util\CodeSnippetCreator::RECURSIVE_PATH,
        'gitHubLink' => 'https://github.com/TYPO3/typo3/blob/main/typo3/sysext/backend/Classes/',
        'mainNamespace' => 'TYPO3\\CMS\\Backend\\',
        'overwriteRst' => true,
        'overwriteIndex' => true,
        'path' => 'Api/Backend/',
    ],
    [
        'action' => 'createPhpClassDocsAll',
        'namespace' => 'TYPO3\CMS\Belog',
        'mode' => HaydenPierce\ClassFinder\ClassFinder::RECURSIVE_MODE,
        'pathMode' => T3docs\RestructuredApiTools\Util\CodeSnippetCreator::RECURSIVE_PATH,
        'gitHubLink' => 'https://github.com/TYPO3/typo3/blob/main/typo3/sysext/belog/Classes/',
        'mainNamespace' => 'TYPO3\\CMS\\Belog\\',
        'overwriteRst' => true,
        'overwriteIndex' => true,
        'path' => 'Api/Belog/',
    ],
    [
        'action' => 'createPhpClassDocsAll',
        'namespace' => 'TYPO3\CMS\Beuser',
        'mode' => HaydenPierce\ClassFinder\ClassFinder::RECURSIVE_MODE,
        'pathMode' => T3docs\RestructuredApiTools\Util\CodeSnippetCreator::RECURSIVE_PATH,
        'gitHubLink' => 'https://github.com/TYPO3/typo3/blob/main/typo3/sysext/beuser/Classes/',
        'mainNamespace' => 'TYPO3\\CMS\\Beuser\\',
        'overwriteRst' => true,
        'overwriteIndex' => true,
        'path' => 'Api/Beuser/',
    ],
    [
        'action' => 'createPhpClassDocsAll',
        'namespace' => 'TYPO3\CMS\Core',
        'mode' => HaydenPierce\ClassFinder\ClassFinder::RECURSIVE_MODE,
        'pathMode' => T3docs\RestructuredApiTools\Util\CodeSnippetCreator::RECURSIVE_PATH,
        'gitHubLink' => 'https://github.com/TYPO3/typo3/blob/main/typo3/sysext/core/Classes/',
        'mainNamespace' => 'TYPO3\\CMS\\Core\\',
        'overwriteRst' => true,
        'overwriteIndex' => true,
        'path' => 'Api/Core/',
    ],
    [
        'action' => 'createPhpClassDocsAll',
        'namespace' => 'TYPO3\CMS\Dashboard',
        'mode' => HaydenPierce\ClassFinder\ClassFinder::RECURSIVE_MODE,
        'pathMode' => T3docs\RestructuredApiTools\Util\CodeSnippetCreator::RECURSIVE_PATH,
        'gitHubLink' => 'https://github.com/TYPO3/typo3/blob/main/typo3/sysext/dashboard/Classes/',
        'mainNamespace' => 'TYPO3\\CMS\\Dashboard\\',
        'overwriteRst' => true,
        'overwriteIndex' => true,
        'path' => 'Api/Dashboard/',
    ],
    [
        'action' => 'createPhpClassDocsAll',
        'namespace' => 'TYPO3\CMS\Extbase',
        'mode' => HaydenPierce\ClassFinder\ClassFinder::RECURSIVE_MODE,
        'pathMode' => T3docs\RestructuredApiTools\Util\CodeSnippetCreator::RECURSIVE_PATH,
        'gitHubLink' => 'https://github.com/TYPO3/typo3/blob/main/typo3/sysext/extbase/Classes/',
        'mainNamespace' => 'TYPO3\\CMS\\Extbase\\',
        'overwriteRst' => true,
        'overwriteIndex' => true,
        'path' => 'Api/Extbase/',
    ],
    [
        'action' => 'createPhpClassDocsAll',
        'namespace' => 'TYPO3\CMS\Extensionmanager',
        'mode' => HaydenPierce\ClassFinder\ClassFinder::RECURSIVE_MODE,
        'pathMode' => T3docs\RestructuredApiTools\Util\CodeSnippetCreator::RECURSIVE_PATH,
        'gitHubLink' => 'https://github.com/TYPO3/typo3/blob/main/typo3/sysext/extensionmanager/Classes/',
        'mainNamespace' => 'TYPO3\\CMS\\Extensionmanager\\',
        'overwriteRst' => true,
        'overwriteIndex' => true,
        'path' => 'Api/Extensionmanager/',
    ],
    [
        'action' => 'createPhpClassDocsAll',
        'namespace' => 'TYPO3\CMS\FrontendLogin',
        'mode' => HaydenPierce\ClassFinder\ClassFinder::RECURSIVE_MODE,
        'pathMode' => T3docs\RestructuredApiTools\Util\CodeSnippetCreator::RECURSIVE_PATH,
        'gitHubLink' => 'https://github.com/TYPO3/typo3/blob/main/typo3/sysext/felogin/Classes/',
        'mainNamespace' => 'TYPO3\\CMS\\FrontendLogin\\',
        'overwriteRst' => true,
        'overwriteIndex' => true,
        'path' => 'Api/FrontendLogin/',
    ],
    [
        'action' => 'createPhpClassDocsAll',
        'namespace' => 'TYPO3\CMS\Filelist',
        'mode' => HaydenPierce\ClassFinder\ClassFinder::RECURSIVE_MODE,
        'pathMode' => T3docs\RestructuredApiTools\Util\CodeSnippetCreator::RECURSIVE_PATH,
        'gitHubLink' => 'https://github.com/TYPO3/typo3/blob/main/typo3/sysext/filelist/Classes/',
        'mainNamespace' => 'TYPO3\\CMS\\Filelist\\',
        'overwriteRst' => true,
        'overwriteIndex' => true,
        'path' => 'Api/Filelist/',
    ],
    [
        'action' => 'createPhpClassDocsAll',
        'namespace' => 'TYPO3\CMS\Fluid',
        'mode' => HaydenPierce\ClassFinder\ClassFinder::RECURSIVE_MODE,
        'pathMode' => T3docs\RestructuredApiTools\Util\CodeSnippetCreator::RECURSIVE_PATH,
        'gitHubLink' => 'https://github.com/TYPO3/typo3/blob/main/typo3/sysext/fluid/Classes/',
        'mainNamespace' => 'TYPO3\\CMS\\Fluid\\',
        'overwriteRst' => true,
        'overwriteIndex' => true,
        'path' => 'Api/Fluid/',
    ],
    [
        'action' => 'createPhpClassDocsAll',
        'namespace' => 'TYPO3\CMS\Frontend',
        'mode' => HaydenPierce\ClassFinder\ClassFinder::RECURSIVE_MODE,
        'pathMode' => T3docs\RestructuredApiTools\Util\CodeSnippetCreator::RECURSIVE_PATH,
        'gitHubLink' => 'https://github.com/TYPO3/typo3/blob/main/typo3/sysext/frontend/Classes/',
        'mainNamespace' => 'TYPO3\\CMS\\Frontend\\',
        'overwriteRst' => true,
        'overwriteIndex' => true,
        'path' => 'Api/Frontend/',
    ],
    [
        'action' => 'createPhpClassDocsAll',
        'namespace' => 'TYPO3\CMS\Info',
        'mode' => HaydenPierce\ClassFinder\ClassFinder::RECURSIVE_MODE,
        'pathMode' => T3docs\RestructuredApiTools\Util\CodeSnippetCreator::RECURSIVE_PATH,
        'gitHubLink' => 'https://github.com/TYPO3/typo3/blob/main/typo3/sysext/info/Classes/',
        'mainNamespace' => 'TYPO3\\CMS\\Info\\',
        'overwriteRst' => true,
        'overwriteIndex' => true,
        'path' => 'Api/Info/',
    ],
    [
        'action' => 'createPhpClassDocsAll',
        'namespace' => 'TYPO3\CMS\Install',
        'mode' => HaydenPierce\ClassFinder\ClassFinder::RECURSIVE_MODE,
        'pathMode' => T3docs\RestructuredApiTools\Util\CodeSnippetCreator::RECURSIVE_PATH,
        'gitHubLink' => 'https://github.com/TYPO3/typo3/blob/main/typo3/sysext/install/Classes/',
        'mainNamespace' => 'TYPO3\\CMS\\Install\\',
        'overwriteRst' => true,
        'overwriteIndex' => true,
        'path' => 'Api/Install/',
    ],
    [
        'action' => 'createPhpClassDocsAll',
        'namespace' => 'TYPO3\CMS\Lowlevel',
        'mode' => HaydenPierce\ClassFinder\ClassFinder::RECURSIVE_MODE,
        'pathMode' => T3docs\RestructuredApiTools\Util\CodeSnippetCreator::RECURSIVE_PATH,
        'gitHubLink' => 'https://github.com/TYPO3/typo3/blob/main/typo3/sysext/lowlevel/Classes/',
        'mainNamespace' => 'TYPO3\\CMS\\Lowlevel\\',
        'overwriteRst' => true,
        'overwriteIndex' => true,
        'path' => 'Api/Lowlevel/',
    ],
    [
        'action' => 'createPhpClassDocsAll',
        'namespace' => 'TYPO3\CMS\Opendocs',
        'mode' => HaydenPierce\ClassFinder\ClassFinder::RECURSIVE_MODE,
        'pathMode' => T3docs\RestructuredApiTools\Util\CodeSnippetCreator::RECURSIVE_PATH,
        'gitHubLink' => 'https://github.com/TYPO3/typo3/blob/main/typo3/sysext/opendocs/Classes/',
        'mainNamespace' => 'TYPO3\\CMS\\Opendocs\\',
        'overwriteRst' => true,
        'overwriteIndex' => true,
        'path' => 'Api/Opendocs/',
    ],
    [
        'action' => 'createPhpClassDocsAll',
        'namespace' => 'TYPO3\CMS\Recordlist',
        'mode' => HaydenPierce\ClassFinder\ClassFinder::RECURSIVE_MODE,
        'pathMode' => T3docs\RestructuredApiTools\Util\CodeSnippetCreator::RECURSIVE_PATH,
        'gitHubLink' => 'https://github.com/TYPO3/typo3/blob/main/typo3/sysext/recordlist/Classes/',
        'mainNamespace' => 'TYPO3\\CMS\\Recordlist\\',
        'overwriteRst' => true,
        'overwriteIndex' => true,
        'path' => 'Api/Recordlist/',
    ],
    [
        'action' => 'createPhpClassDocsAll',
        'namespace' => 'TYPO3\CMS\Recycler',
        'mode' => HaydenPierce\ClassFinder\ClassFinder::RECURSIVE_MODE,
        'pathMode' => T3docs\RestructuredApiTools\Util\CodeSnippetCreator::RECURSIVE_PATH,
        'gitHubLink' => 'https://github.com/TYPO3/typo3/blob/main/typo3/sysext/recycler/Classes/',
        'mainNamespace' => 'TYPO3\\CMS\\Recycler\\',
        'overwriteRst' => true,
        'overwriteIndex' => true,
        'path' => 'Api/Recycler/',
    ],
    [
        'action' => 'createPhpClassDocsAll',
        'namespace' => 'TYPO3\CMS\Redirects',
        'mode' => HaydenPierce\ClassFinder\ClassFinder::RECURSIVE_MODE,
        'pathMode' => T3docs\RestructuredApiTools\Util\CodeSnippetCreator::RECURSIVE_PATH,
        'gitHubLink' => 'https://github.com/TYPO3/typo3/blob/main/typo3/sysext/redirects/Classes/',
        'mainNamespace' => 'TYPO3\\CMS\\Redirects\\',
        'overwriteRst' => true,
        'overwriteIndex' => true,
        'path' => 'Api/Redirects/',
    ],
    [
        'action' => 'createPhpClassDocsAll',
        'namespace' => 'TYPO3\CMS\Reports',
        'mode' => HaydenPierce\ClassFinder\ClassFinder::RECURSIVE_MODE,
        'pathMode' => T3docs\RestructuredApiTools\Util\CodeSnippetCreator::RECURSIVE_PATH,
        'gitHubLink' => 'https://github.com/TYPO3/typo3/blob/main/typo3/sysext/reports/Classes/',
        'mainNamespace' => 'TYPO3\\CMS\\Reports\\',
        'overwriteRst' => true,
        'overwriteIndex' => true,
        'path' => 'Api/Reports/',
    ],
    [
        'action' => 'createPhpClassDocsAll',
        'namespace' => 'TYPO3\CMS\RteCKEditor',
        'mode' => HaydenPierce\ClassFinder\ClassFinder::RECURSIVE_MODE,
        'pathMode' => T3docs\RestructuredApiTools\Util\CodeSnippetCreator::RECURSIVE_PATH,
        'gitHubLink' => 'https://github.com/TYPO3/typo3/blob/main/typo3/sysext/rte_ckeditor/Classes/',
        'mainNamespace' => 'TYPO3\\CMS\\RteCKEditor\\',
        'overwriteRst' => true,
        'overwriteIndex' => true,
        'path' => 'Api/RteCKEditor/',
    ],
    [
        'action' => 'createPhpClassDocsAll',
        'namespace' => 'TYPO3\CMS\Scheduler',
        'mode' => HaydenPierce\ClassFinder\ClassFinder::RECURSIVE_MODE,
        'pathMode' => T3docs\RestructuredApiTools\Util\CodeSnippetCreator::RECURSIVE_PATH,
        'gitHubLink' => 'https://github.com/TYPO3/typo3/blob/main/typo3/sysext/scheduler/Classes/',
        'mainNamespace' => 'TYPO3\\CMS\\Scheduler\\',
        'overwriteRst' => true,
        'overwriteIndex' => true,
        'path' => 'Api/Scheduler/',
    ],
    [
        'action' => 'createPhpClassDocsAll',
        'namespace' => 'TYPO3\CMS\Seo',
        'mode' => HaydenPierce\ClassFinder\ClassFinder::RECURSIVE_MODE,
        'pathMode' => T3docs\RestructuredApiTools\Util\CodeSnippetCreator::RECURSIVE_PATH,
        'gitHubLink' => 'https://github.com/TYPO3/typo3/blob/main/typo3/sysext/seo/Classes/',
        'mainNamespace' => 'TYPO3\\CMS\\Seo\\',
        'overwriteRst' => true,
        'overwriteIndex' => true,
        'path' => 'Api/Seo/',
    ],
    [
        'action' => 'createPhpClassDocsAll',
        'namespace' => 'TYPO3\CMS\SysNote',
        'mode' => HaydenPierce\ClassFinder\ClassFinder::RECURSIVE_MODE,
        'pathMode' => T3docs\RestructuredApiTools\Util\CodeSnippetCreator::RECURSIVE_PATH,
        'gitHubLink' => 'https://github.com/TYPO3/typo3/blob/main/typo3/sysext/sys_note/Classes/',
        'mainNamespace' => 'TYPO3\\CMS\\SysNote\\',
        'overwriteRst' => true,
        'overwriteIndex' => true,
        'path' => 'Api/SysNote/',
    ],
    [
        'action' => 'createPhpClassDocsAll',
        'namespace' => 'TYPO3\CMS\T3editor',
        'mode' => HaydenPierce\ClassFinder\ClassFinder::RECURSIVE_MODE,
        'pathMode' => T3docs\RestructuredApiTools\Util\CodeSnippetCreator::RECURSIVE_PATH,
        'gitHubLink' => 'https://github.com/TYPO3/typo3/blob/main/typo3/sysext/t3editor/Classes/',
        'mainNamespace' => 'TYPO3\\CMS\\T3editor\\',
        'overwriteRst' => true,
        'overwriteIndex' => true,
        'path' => 'Api/T3editor/',
    ],
    [
        'action' => 'createPhpClassDocsAll',
        'namespace' => 'TYPO3\CMS\Tstemplate',
        'mode' => HaydenPierce\ClassFinder\ClassFinder::RECURSIVE_MODE,
        'pathMode' => T3docs\RestructuredApiTools\Util\CodeSnippetCreator::RECURSIVE_PATH,
        'gitHubLink' => 'https://github.com/TYPO3/typo3/blob/main/typo3/sysext/tstemplate/Classes/',
        'mainNamespace' => 'TYPO3\\CMS\\Tstemplate\\',
        'overwriteRst' => true,
        'overwriteIndex' => true,
        'path' => 'Api/Tstemplate/',
    ],
    [
        'action' => 'createPhpClassDocsAll',
        'namespace' => 'TYPO3\CMS\Viewpage',
        'mode' => HaydenPierce\ClassFinder\ClassFinder::RECURSIVE_MODE,
        'pathMode' => T3docs\RestructuredApiTools\Util\CodeSnippetCreator::RECURSIVE_PATH,
        'gitHubLink' => 'https://github.com/TYPO3/typo3/blob/main/typo3/sysext/viewpage/Classes/',
        'mainNamespace' => 'TYPO3\\CMS\\Viewpage\\',
        'overwriteRst' => true,
        'overwriteIndex' => true,
        'path' => 'Api/Viewpage/',
    ],
    [
        'action' => 'createPhpClassDocsAll',
        'namespace' => 'TYPO3\CMS\Workspaces',
        'mode' => HaydenPierce\ClassFinder\ClassFinder::RECURSIVE_MODE,
        'pathMode' => T3docs\RestructuredApiTools\Util\CodeSnippetCreator::RECURSIVE_PATH,
        'gitHubLink' => 'https://github.com/TYPO3/typo3/blob/main/typo3/sysext/workspaces/Classes/',
        'mainNamespace' => 'TYPO3\\CMS\\Workspaces\\',
        'overwriteRst' => true,
        'overwriteIndex' => true,
        'path' => 'Api/Workspaces/',
    ],/**/
];

/*
    return array_merge(
        include('Config/EventsBackend.php'),
        include('Config/EventsCore.php'),
        include('Config/EventsCoreResource.php'),
        include('Config/EventsExtbase.php'),
        include('Config/EventsExtensionManager.php'),
        include('Config/EventsFilelist.php'),
        include('Config/EventsFrontend.php'),
        include('Config/EventsFrontendLogin.php'),
        include('Config/EventsImpexp.php'),
        include('Config/EventsInfo.php'),
        include('Config/EventsInstall.php'),
        include('Config/EventsLinkvalidator.php'),
        include('Config/EventsRecordlist.php'),
        include('Config/EventsRedirects.php'),
        include('Config/EventsSeo.php'),
        include('Config/EventsSetup.php'),
        include('Config/EventsWorkspaces.php'),
    );
*/